# Generated by Django 4.1 on 2023-04-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_booking_paymentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='paymentstatus',
            field=models.CharField(default='paid', max_length=20),
        ),
    ]
